### PR TITLE
5.x dump test uses the new dump command semantics

### PR DESCRIPTION
**Pull request by PetrJanouch**

### CODE REVIEW

**Review by MishaDemianenko — APPROVED** [review]

**Review by MishaDemianenko — COMMENTED** [review]
Looks good except that will fail for old versions

**Comment by PetrJanouch** [comment]
@MishaDemianenko Why? The test should be used only for 5.x images. 4.x has another test. At least to my understanding.

**Comment by MishaDemianenko** [comment]
> @MishaDemianenko Why? The test should be used only for 5.x images. 4.x has another test. At least to my understanding.

not in this repo. Check for example https://github.com/neo4j/docker-neo4j/blob/master/src/test/java/com/neo4j/docker/neo4jadmin/TestBackupRestore.java and TestBackupRestore44 over there.
There are checks like `Assumptions.assumeTrue( TestSettings.NEO4J_VERSION.isAtLeastVersion( Neo4jVersion.NEO4J_VERSION_500 )` and as you can see old versions are executed on top of your PR

**Comment by MishaDemianenko** [comment]
@jennyowen can correct we if i'm wrong and something changed here (but not according to tesst code) ^^^

**Comment by PetrJanouch** [comment]
That is really weird. the test I fixed already uses 5.x-only command semantics. It uses `neo4j-admin database dump`, which is something 4.x will not understand.

**Comment by MishaDemianenko** [comment]
hm looks like that test class `TestDumpLoad` has this thing `Assumptions.assumeTrue( TestSettings.NEO4J_VERSION.isAtLeastVersion( Neo4jVersion.NEO4J_VERSION_500 ),` as part of `beforeAll` so version protection should be covered but that i suppose and we should be good

**Comment by MishaDemianenko** [comment]
> > @MishaDemianenko Why? The test should be used only for 5.x images. 4.x has another test. At least to my understanding.
> 
> not in this repo. Check for example https://github.com/neo4j/docker-neo4j/blob/master/src/test/java/com/neo4j/docker/neo4jadmin/TestBackupRestore.java and TestBackupRestore44 over there. There are checks like `Assumptions.assumeTrue( TestSettings.NEO4J_VERSION.isAtLeastVersion( Neo4jVersion.NEO4J_VERSION_500 )` and as you can see old versions are executed on top of your PR

Whole class is already under version check so we should be good

**Comment by jennyowen** [comment]
Yep, that test is 5.0 for reasons you already figured out. Looks good!

**Pull request merged**
