### PR TITLE
Separate arg for initial heap size

### PR DESCRIPTION
**Pull request by MkhIr**

### CODE REVIEW

**Comment by benbc** [comment]
@MkhIr Can you tell me why this would be useful to you? Our experience is that it's easier to manage Neo4j if the entire heap is allocated immediately.

**Comment by benbc** [comment]
@MkhIr You only need to change `docker-entrypoint.sh` in the root of the codebase as we won't retrospectively change already-released images.

**Comment by MkhIr** [comment]
@benbc  in an experiment I was making It was causing issue when assigning more that 75% of the sys ram (in my case 52 of 64). Having separate arg would allow allocation of acceptable number with a max heap for cases such as loading large csv or match.

**Comment by benbc** [comment]
@MkhIr It sounds like your envisaging a case where you'll run an operation (e.g. loading large CSV) that may or may not work at random depending on what else is going on on the machine at the time. It's avoiding exactly this kind of uncertainty that leads us to recommend setting a fixed size for the heap.

**Comment by benbc** [comment]
@MkhIr Are you still interested in this change?

**Comment by MkhIr** [comment]
no you can ignore it if thats the case.

**Pull request closed without merging**
