### PR TITLE
Updated default host of neo4j

### PR DESCRIPTION
**Pull request by ikwattro**
Docker doesn't run on localhost. I don't know however if `192.168.99.100` is the default docker host ip on all platforms.

### CODE REVIEW

**Comment by jbhannah** [comment]
This only applies on platforms where Docker Machine is necessary (i.e. OS X and Windows); a note, for example, to

> replace `localhost` with your Docker Machine IP address on OS X and Windows

would suffice, instead of making Docker Machine the default assumption.

**Comment by ikwattro** [comment]
@jbhannah cool nice to know. I'll amned with your suggestion.

**Comment by benbc** [comment]
@ikwattro Thanks for raising this. We have had several people run into similar problems on OSX. We're going to try to figure out the best way of avoiding this. (The trouble is that it's not just this `http://localhost:7474` bit that catches people out -- there is stuff with mounting volumes that differs on OSX as well.)

**Comment by benbc** [comment]
I've added some help text in https://github.com/neo4j/docker-neo4j/commit/24259da41e1c6ca88f5e6cdd44146b5d810c156c.

**Pull request closed without merging**
