### PR TITLE
Dockerfile and script for the 2.1.7-enterprise version

### PR DESCRIPTION
**Pull request by ursuad**
Hello, 

I needed a 2.1.7 Enterprise version and I couldn't find it in the official repo, so I created one and thought  to contribute.

### CODE REVIEW

**Comment by ursuad** [comment]
Also added files for the Neo4J 2.1.7 community edition.

**Comment by benbc** [comment]
Hello @ursuad. Thanks for raising this. I'm going to have to get some guidance from our product owners about publishing images for old releases. I'll get back to you in a day or two.

**Comment by ursuad** [comment]
Ok, awesome. :+1:

**Comment by benbc** [comment]
@ursuad We're okay to publish the 2.1.7 image, but it needs implementing slightly differently. You need to add the version [here](https://github.com/neo4j/docker-neo4j/blob/master/Makefile#L13), then run `make` and it will generate the files. (See [here](https://github.com/neo4j/docker-neo4j/blob/master/DEVELOPMENT.md) for how to set up a development environment.)

We can probably do this ourselves in the next week if you don't get to it.

If you'd like to include the IntelliJ files in `.gitignore`, can you please just add the minimum necessary to that file?

**Comment by ursuad** [comment]
Yes, sure. I'll take a look.

**Comment by benbc** [comment]
@ursuad I've just published `neo4j/neo4j:2.1.7`.

**Pull request closed without merging**
