### PR TITLE
Docker entrypoint should not chmod or chown folders

### PR DESCRIPTION
**Pull request by rweverwijk**
This PR should solve permission issues with mounted folders.
The idea is that the provider of the mount is responsible for correct permissions for the docker image.

The entrypoint should check the correctness of the used mounts and give correct pointers to the user to help if there are missing permissions.

This PR should solve #164

### CODE REVIEW

**Comment by jennyowen** [comment]
Hi Ron, sorry for the wait. I was on vacation, but now I'm on the case!

The 3.5 tests failed with the error:
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "chdir to cwd (\"/var/lib/neo4j\") set in config.json failed: permission denied": unknown.`
`ERROR (test-starts-up-with-data-volume-and-user): trap on error (rc=126) near line 104`

I assume "line 104" refers to this, where the container is started:
https://github.com/neo4j/docker-neo4j/blob/master/test/helpers.sh#L104

Did you get that error when you run the tests locally? I realise we have no information about how to actually run these tests, so for 3.5 it's:

```
export NEO4J_VERSION=3.5.3
make clean test
```

**Comment by rweverwijk** [comment]
Hi Jenny,

I didn't know how to run them, I will take a look at them tomorrow night.

Cheers,
Ron

**Comment by rweverwijk** [comment]
small update from my side. Had some trouble running the test as it didn't work on OSX out of the box . Needed a test env with GNU tooling.

Setup is now correct I thing so will take a look at the issues this week.

**Comment by rweverwijk** [comment]
hi @jennyowen,

At can you take a look again? tests run successfully on my machine, can't see the log of the failing build in TeamCity.

Cheers,
Ron

**Comment by jennyowen** [comment]
@rweverwijk a couple of things.

1) Before I can accept the PR I'll need you to agree to our Contributor License Agreement here:
https://neo4j.com/developer/cla/
It's a one page document, and agreement just requires sending an email. Details are in the link.

2) It's very important we don't break functionality for existing users. Requiring users to `chmod` the mount folders before running the neo4j container would do that.
The promised behaviour for the current containers is that this should **just work**:
```bash
docker run \
    --publish=7474:7474 --publish=7687:7687 \
    --volume=$HOME/neo4j/data:/data \
    --volume=$HOME/neo4j/logs:/logs \
    neo4j:3.5
```
We can't break that functionality in a patch, it has to wait for a new major/minor release.
What we can (and should) be doing is checking that the user can read and write to the mounted folders, and doing a `chmod` **only** if they cannot. There should also be better advice about how to fix permissions error when they arise. 

The current behaviour of automatically editing the folder permissions is definitely wrong, and your PR improves the error messaging and the permission checking immensely. However, I'll still need to make some modification so that it's compatible with the current workflow. Hope that's OK?

**Comment by rweverwijk** [comment]
Hi Jenny.

1) I'm already in the system since Match 4th 2016
2) I'm okay with modifications, you can continue with this PR, use this as inspiration or completely ignore and close this, all fine by me and up to you ;)

**Comment by jennyowen** [comment]
Hi Ron, excellent!
I've adapted your changes and fixed some bugs I found.
The container will still change the owner on mounted folders if the `--user` flag isn't supplied, but it should no longer `chmod` everything to allow all users to read/write.

For your use case, I'd recommend supplying the user and group IDs to `docker run` (if you weren't already). That's the docker recommended way of mounting host folders, since the process and folder will be owned by the same user.
```
docker run \
   -p 7474:7474 -p 7687:7687 \
   --user "$(id -u):$(id -g)" \
   -v /etc/passwd:/etc/passwd:ro \
   -v OTHERMOUNTS... \
    neo4j:latest
```

The changes should be in the following patches onwards:
- 3.3.10
- 3.4.14
- 3.5.6

**Pull request merged**
